/**
 * 🚨 此文件由 CloudEnableTool 自动生成，请勿手动修改！
 * This file is auto-generated by CloudEnableTool. Do not edit manually!
 */

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function getSupabaseUrl(): string {
  return `${(window as any).MEOO_CONFIG?.meoo_app_access_url || location.origin}/sb-api`;
}

export const supabaseUrl = getSupabaseUrl();
export const supabaseAnonKey = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzc2MzUwMzAwLCJleHAiOjEzMjg2OTkwMzAwfQ.2VrqhDjFmt76bDLqbQcUK3in3N4Z8bm32p-krCXfYSk';

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});
